### PR TITLE
Add build step, change import patterns

### PR DESCRIPTION
**Pull request by dasulit**
This is a first shot at reorganizing this project a little bit. 🤠 

@tristen I would love for an initial high-level review of the strategy here! I have no idea if this is conventional and am very open to changing paths if you have ideas. Of note is the `build-dist` script, which does the following:
* Reconstructs the `src/gazetteer` subdirectories and (minified) files in `dist`.
* Populates an `index.js` at the root of `dist` with exports for all those gazetteers (maybe this is bad?).
* Also writes `src/util` files to `dist`. The exports for utils are manually maintained in `src`, but merged into the `dist/index.js` file mentioned above (maybe this is bad?).

At the end of the day imports then look like:

`import { globalTransit, lint } from '@mapbox/gazetteer'`

My initial goal was to have nested paths with default exports like: `import transit from '@mapbox/gazetteer/transit'` but there isn't really a straightforward way to accomplish this without an over-the-top build script. So landing on named exports, though I don't love the export names and would be very open to other ideas.

If you 👍the approach, I can address the rest of https://github.com/mapbox/gazetteer/issues/51 and maybe https://github.com/mapbox/gazetteer/issues/48. If not, maybe we can workshop some alternatives?

### CODE REVIEW

**Comment by tristen** [comment]
Is another option not writing a dist script and requiring a user to request gazetteers by writing path out in the require like this https://runkit.com/embed/r8dw0kvjn0bp?

Instead of `@mapbox/gazetteer/mapbox-streets/natural-label.json` with [reorganization](#51) it could be `@mapbox/gazetteer/locations/global/natural-label.json`?

**Comment by dasulit** [comment]
@tristen that's possible, but the paths seemed unwieldy to me 😕 do you not think so?

**Comment by tristen** [comment]
Just spitballing but something like this could be nice?

```js
import { global, japan } from '@mapbox/gazetteer/locations'
const { transit, buildings } = global; 
```

So each directory under locations would have its own `index.js` that exports all the gazetteers within the directory?

```js
module.exports = {
  transit: require('./transit'),
  buildings: require('./buildings')
};
```


cc/ @mapbox/map-design-team for other ideas?

**Comment by dasulit** [comment]
@tristen HELLO! 1 month later, giving this another pass 😭 the latest commit strips out all of the build nonsense, and reflects your most recent proposal. Would you mind reviewing to see if this looks as expected to you?

**Pull request merged**
